- name: install apache2 on dev
  hosts: dev
  tasks:
    - name: create apache2
      apt:
        name: apache2
        state: present
    #- name: create /tmp/index.html file
    #  copy:
    #    dest: "/tmp/index.html"
    #    content: |
    #      Ansible delivered
    - name: copy /tmp/index.html to /var/www/html/index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
    - name: start and enable apache2
      service:
        name: apache2
        state: started
        enabled: yes

